[build-system]
requires = ["setuptools>=61.0", "torch", "numpy"]
build-backend = "setuptools.build_meta"

[project]
name = "lib8"
version = "0.0.1"
description = "A sample local library for demonstration."
